import type { Metadata } from "next";
// Utilisation de CSS standard pour les polices au lieu de next/font/google
import "./globals.css";
import { ThemeProvider } from "@/contexts/ThemeContext";

// Nous utiliserons des polices système au lieu des polices Google pour éviter les problèmes avec Turbopack

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning={true}>
      <body
        className="font-sans antialiased"
      >
        <ThemeProvider>
          {children}
        </ThemeProvider>
      </body>
    </html>
  );
}
